use TCP for public IP check, bug fixes

diff --git a/bin/ipls b/bin/ipls
--- a/bin/ipls
+++ b/bin/ipls
@@ -1,30 +1,37 @@
 #!/usr/bin/env bash
+# shellcheck disable=SC2086
 
 # list only the IPs for all interfaces
 ipls() {
-  local action output ipv='' labels=false interface ipcmd
+  local output ipv='' labels=false interface ipcmd
 
-  action="${1}"
-
-  local optspec="46ahli:"
+  local cmd="ipls"
+  local optspec="46ahli:p"
   local usage="ipls [-i <interface>] [-46la]
 
--4, -6
+-4, -6            Show only IPv4 or IPv6 addresses
 -a                Show labels
 -i <interface>    Show IPs from specific interface
 -l                List interfaces
-  "
+-p                Show public IP address"
 
   hash ifconfig 2>/dev/null && ipcmd=("ifconfig" "-a") || ipcmd=("ip" "-o" "addr" "show" "")
 
   while getopts "${optspec}" opt
   do
     case "${opt}" in
-      (4|6) ipv="${opt}"  ;;
+      (4|6) 
+        if [[ -z "${ipv}" ]]; then
+          ipv="${opt}" 
+        else 
+          echo "${cmd}: -4 and -6 cannot be used together" 1>&2
+          return 1
+        fi
+        ;;
       (a) labels=true  ;;
       (i) interface="${OPTARG}"  ;;
       (l)
-        if [[ "${ipcmd[@]:0:1}" == "ip" ]]; then
+        if [[ "${ipcmd[*]:0:1}" == "ip" ]]; then
           command ${ipcmd[*]} | awk '{split($4, a, "/"); print $2"}' | sort
         else
           command ${ipcmd[*]} | sed -E 's/[[:space:]:].*//;/^$/d' | sort
@@ -32,33 +39,37 @@ ipls() {
         return
         ;;
       (h) echo "${usage}"; return ;;
+      (p) dig +short +tcp myip.opendns.com @resolver1.opendns.com; return ;;
+      (:|?) return 1 ;;
     esac
   done
 
   if [[ "${labels}" == false ]] && [[ -z "${interface}" ]]; then
-#        output="$(ifconfig | grep "inet" | grep -v "127.0.0.1" | grep -v "::1" | cut -d" "  -f2 | cut -d"%" -f1 | sort)"
-      output=$(command ${ipcmd[*]} | grep -o 'inet6\? \(addr:\)\?\s\?\(\(\([0-9]\+\.\)\{3\}[0-9]\+\)\|[a-fA-F0-9:]\+\)' | awk '{ sub(/inet6? (addr:)? ?/, ""); print }')
+      output=$(command ${ipcmd[*]} | 
+        grep -o 'inet6\? \(addr:\)\?\s\?\(\(\([0-9]\+\.\)\{3\}[0-9]\+\)\|[a-fA-F0-9:]\+\)' |
+        awk '{ sub(/inet6? (addr:)? ?/, ""); print }')$'\n'
   else 
     if [[ -n "${interface}" ]]; then
       while read -r ip; do
         if [ -n "${ip}" ]; then
-          output="${output}${ip}\n"
+          output="${output}${ip}"$'\n'
           fi 
-      done < <(command ${ipcmd[*]:0:-1} "${interface}" | grep "inet" | sed -e 's/^[ \t]*//' | cut -d" "  -f2 | cut -d"%" -f1)
+      done < <(command ${ipcmd[*]::${#ipcmd[@]}-1} "${interface}" | 
+        grep "inet" | sed -e 's/^[ \t]*//' | cut -d" "  -f2 | cut -d"%" -f1)
     else
       # list all interfaces
       
-      if [[ "${ipcmd[@]:0:1}" == "ip" ]]; then
+      if [[ "${ipcmd[*]:0:1}" == "ip" ]]; then
         command ${ipcmd[*]} | awk '{split($4, a, "/"); print $2" : "a[1]}'
       else
         while read -r interface; do
           # get ip for each interface
           while read -r ip; do
             if [ -n "${ip}" ]; then
-              output="${output}${interface} : ${ip}
-"
+              output="${output}${interface} : ${ip}"$'\n'
               fi 
-          done < <(command ${ipcmd[@]:0:1} "${interface}" | grep "inet" | sed -e 's/^[ \t]*//' | cut -d" "  -f2 | cut -d"%" -f1)
+          done < <(command ${ipcmd[*]:0:1} "${interface}" | 
+            grep "inet" | sed -e 's/^[ \t]*//' | cut -d" "  -f2 | cut -d"%" -f1)
         done < <(command ${ipcmd[*]} | sed -E 's/[[:space:]:].*//;/^$/d')
       fi
     fi
@@ -66,14 +77,14 @@ ipls() {
 
   case "${ipv}" in 
     4)
-        echo "${output}" | grep -v ":"
-        ;;
+      printf "%s" "${output}" | grep "\."
+      ;;
     6)
-        echo "${output}" | grep -v "\."
-        ;;
+      printf "%s" "${output}" | grep -v "\."
+      ;;
     *)
-      echo "${output}"
+      printf "%s" "${output}"
   esac
 }
 
-ipls $@
+ipls "${@}"
